# Generated by Django 3.1.4 on 2021-01-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemForm', '0003_auto_20210103_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='profit',
            new_name='sold_price',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(max_length=15),
        ),
    ]
