# Generated by Django 3.1.4 on 2021-01-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemForm', '0004_auto_20210107_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sold_date',
        ),
    ]
