# Generated by Django 3.1.4 on 2021-01-15 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemForm', '0005_auto_20210107_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inserted_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
